-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public."MyDimDate"(dateid integer NOT NULL, date date NOT NULL, year integer NOT NULL, quarter integer NOT NULL, quartername "char" NOT NULL, month integer NOT NULL, monthname "char" NOT NULL, day integer NOT NULL, weekday integer NOT NULL, weekdayname "char" NOT NULL, PRIMARY KEY (dateid));

CREATE TABLE public."MyDimTruck" (Truckid integer NOT NULL, TruckType "char" NOT NULL, PRIMARY KEY (Truckid));

CREATE TABLE public."MyDimStation" (stationid integer NOT NULL, city "char" NOT NULL, PRIMARY KEY (stationid));

CREATE TABLE public."MyFactTrips" (tripid integer NOT NULL, dateid integer NOT NULL, stationid integer NOT NULL, Truckid integer NOT NULL, Wastecollected numeric NOT NULL, PRIMARY KEY (tripid));

ALTER TABLE public."MyFactTrips" ADD FOREIGN KEY (dateid) REFERENCES public."MyDimDate" (dateid) NOT VALID;


ALTER TABLE public."MyFactTrips" ADD FOREIGN KEY (Truckid) REFERENCES public."MyDimTruck" (Truckid) NOT VALID;

ALTER TABLE public."MyFactTrips" ADD FOREIGN KEY (stationid) REFERENCES public."MyDimStation" (stationid) NOT VALID;

END;

SELECT stationid, trucktype, sum(Wastecollected) FROM DNwaste 
	GROUP BY GROUPING SETS(stationid, trucktype)

SELECT year, city, stationid, sum(Wastecollected) FROM DNwaste 
	GROUP BY year, city, stationid

SELECT year, city, stationid, average(Wastecollected) FROM DNwaste 
	GROUP BY CUBE(year, city, stationid),
	Order by year, city, stationid;

CREATE TABLE MQT As (SELECT city, stationid, trucktype, max(Wastecollected) FROM DNwaste 
	GROUP BY trucktype, city, stationid)
DATA INITIALLY IMMEDIATE  REFRESH DEFERRED 
ENABLE QUERY OPTIMIZATION
